import type { ProviderRegistration } from "@getpaseo/plugin/server/provider";

/**
 * Typed facade over server/claude-provider.dist.cjs (generated by
 * `npm run build`). Intentionally self-contained: importing the provider
 * source here would drag the claude-agent-sdk type surface back into the
 * daemon compiler's dependency walk, which is what the bundle avoids.
 */
export declare function createTranslateClaudeProvider(deps: {
  /** Loads validated translate settings; rejects while unconfigured. */
  loadConfig(): Promise<Record<string, unknown>>;
  /** Translation endpoint override for tests. */
  fetchFn?: typeof fetch;
  /** Translation cache store; injects the shared persistent one in production. */
  cacheStore?: {
    get(key: string): string | undefined;
    set(key: string, value: string): void;
  };
  /** Query factory override for tests. */
  queryFactory?: (params: { prompt: AsyncIterable<unknown>; options: unknown }) => {
    interrupt(): Promise<unknown>;
    [Symbol.asyncIterator](): AsyncIterator<unknown>;
  };
}): ProviderRegistration;
